### ISSUE TITLE
1.4.8 Game crashes while starting up in the Completing Minecraft Installation Stage while Loading Textures

### ISSUE THREAD

**Issue by qwsxedcrfv** [scalda/FoolCraft#330]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
After starting up FoolCraft, the game starts to load and initialize normally, but once it reaches the Finishing Up stage (just as or before texture reloading), the screen flashes black and the game freezes, forcing me to shut it down with task manager. I've tried using all the various versions, importing the data to my normal minecraft launcher, and installing the corresponding version of forge. None of them work, and allocating more data does nothing.

## Reproduce Steps
1. Open pack
2. Start up pack (changing settings does not matter)
3. Wait for Completing Minecraft Installation Stage (7/7)
4. Crash (somehow)?

## Additional Information
This is a continuation of issues #97 and #199, but the problem has persisted until now.
NOTE: This pastebin was extracted from older versions since the output log fails when the game freezes (and does not respond when starting up for some reason)
https://pastebin.com/qXaHd4H0
Also tried with 1.3.1, nothing changes
stops right around the grandfather clock texture

**Comment by scalda** [comment]
please try a clean install

**Comment by qwsxedcrfv** [comment]
I have

**Comment by Jefferson4420** [comment]
Exact same issue I have had from the beginning of this modpack. I installed a "clean" updated version today, and the same thing happens as before.

**Comment by scalda** [comment]
can you please send me the full client log?

**Comment by Jefferson4420** [comment]
OLD launcher log https://pastebin.com/HKAwvvw2
Game output log https://pastebin.com/ju9CLKpH
The new launcher does the same thing, just doesn't give me a log report.

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda

**Comment by Jefferson4420** [comment]
This did not fix anything. The same exact issue as before. The loading freezes in the final stages during clientproxy.
Please help!

**Comment by Jefferson4420** [comment]
This is the first modpack that I am unable to play! I have played all of the larger and more popular packs, in many different versions of Minecraft. I am a very experienced player and used to do Youtube LPs. 
WHY IS THIS THE ONLY PACK THAT DOESN'T WORK FOR ME?

**Comment by lolman2810** [comment]
has this issue been solved by anyone?

**Comment by qwsxedcrfv** [comment]
nope

**Comment by qwsxedcrfv** [comment]
@scalda this was/is not a world corruption issue, it still happens and I have not been able to successfully start up the pack even once, let alone create a world. This problem has persisted through multiple versions and has still not been fixed. A list of other issues that appear to be older or newer reposts/versions of this:
#460 
#446 
Possible solution? #358 
+the ones mentioned in the original post

**Comment by scalda** [comment]
Please update Java, that is a common thing between all these issues and also remove optifine til you can get the pack loaded successfully. also more info about system specs would be nice to see if it can be narrowed down further?

**Comment by qwsxedcrfv** [comment]
I've been using the latest version of Java, and I have not changed the default mods, so no Optifine. I'm using Java 1.8.0.131, 64-bit, and I have 6G allocated.
Windows 10 Pro, 
Processer: Intel(R) Xeon(R) CPU E31240 @ 3.30 GHZ   3.30 GHz
Tell me if you need anything else

**Comment by ajdjyt** [comment]
This is a BOP problem read lines around  929 to 937

**Comment by qwsxedcrfv** [comment]
@ajdjyt please be specific, which text are you looking at?

**Comment by qwsxedcrfv** [comment]
I'm not sure if I understand how it could be fixed, or if it is even COFH that is actually causing the problem. It could just be detecting an error caused by a different mod.

**Comment by scalda** [comment]
please try 1.4.4 of the pack as we have found a mod that was causing a major memory leak and we have removed it in this release

**Comment by qwsxedcrfv** [comment]
@scalda Nope, still does not work. No visible changes, but I've included a new pastebin just in case
https://pastebin.com/DGfyFBPS

**Comment by sukiplays** [comment]
I'm having the same issue 7/7 grandfather clock and it just stops responding glad to see I'm not alone on this.

**Comment by mcmodder12** [comment]
i keep getting stuck on 7/7 stuffed creeper for 1.3.3

**Comment by MCKiller22** [comment]
I'm having the same problem, I get stuck on 7/7 stuffed creeper for 1.4.8

**Comment by qwsxedcrfv** [comment]
If anyone knows of any posts that have this issue, it would be appreciated if you could reference them here, so everyone has access to the solution when its found.

**Comment by qwsxedcrfv** [comment]
GUYS This issue has been solved for me in Foolcraft 2.0, If this has started working for you, please let others know.
