### ISSUE TITLE
Block duplication with builders wand

### ISSUE THREAD

**Issue by Syntasu** [scalda/FoolCraft#404]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The builders wand from Extra Utilities will place blocks but will not use any blocks from the inventory. If you have 2 blocks you can effectively make infinitly many of them. 

## Reproduce Steps

1) Get 2 blocks
2) Place one block
3) Use the builders wand on the block
4) Repeat for how ever many blocks you want.

Result will be that you placed a new block without consuming the one in your inventory. Pretty serious and game breaking bug I would say.

## Additional Information

This bug has been reported onto the XU2 github page:

https://github.com/rwtema/extrautilities/issues/1454
https://github.com/rwtema/extrautilities/issues/1439
https://github.com/rwtema/extrautilities/issues/1111

**My suggested action is to disable the XU2 Builders wands and force players to use the builders wand of the mod "Better Builders Wands"**.

**Comment by legodude17** [comment]
All of those links are broken.

**Comment by Syntasu** [comment]
Fixed.

**Comment by Jo-Mamma75** [comment]
Fixed in 1.3.3 which is now available.

**Comment by SkippyMitch** [comment]
I'm using 1.10.2 - 1.4.1  and I just noticed this is happening. It took me a while notice it :+1:

**Comment by suprra** [comment]
Same as ^^ same versions and the block dupe is still happening.

**Comment by AlanBTG** [comment]
1.6.1 in Forever Stranded Modpack, block duper still happening.

**Comment by WhatThePuckPT** [comment]
I may have figured out the issue - the Builders Wand functions are swapped between **Survival** and **Creative**. I noticed after some testing that it uses up the blocks in Creative, then swapped to Survival and no blocks were used.

**Comment by cc2k** [comment]
1.10.2-1.7.4  still has this bug.
just confirmed it.

with modeed blocks but also regular cobblestone
