### ISSUE TITLE
Minimoos in Minefactory Autospawner cause crash [Foolcraft 2.2]

### ISSUE THREAD

**Issue by BarryAsthma** [scalda/FoolCraft#783]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Reproducing Minimoos in the Minefactory Autospawner causes the savefile to become corrupted and the game to crash upon reloading the world. 

I first replaced the fluidcow inside my safarinet with a minimoo before I turned on the spawner. When I tried to make an exact copy of the minimoo it didn't work at all. When I tried to make random copies, it did work. However my world soon became corrupted as I was unable to place blocks on certain places. After I tried to reload the save, the game crashed immeditaly aftrer loading the world (see crash reports). 
These crashes kept happening, so I was forced to roll back to Foolcraft 2.1 and reload a backup save.      

## Additional Information
[crash-2017-10-03_21.15.53-server.txt](https://github.com/scalda/FoolCraft/files/1355343/crash-2017-10-03_21.15.53-server.txt)
[crash-2017-10-03_21.18.25-server.txt](https://github.com/scalda/FoolCraft/files/1355415/crash-2017-10-03_21.18.25-server.txt)
[crash-2017-10-03_21.18.36-client.txt](https://github.com/scalda/FoolCraft/files/1355417/crash-2017-10-03_21.18.36-client.txt)

**Comment by RicardoTheCoder** [comment]
RicardoTheCoder/MiniMoos#3 I already gave an answer about that here, for future reference try not use MFR AutoSpawners till this problem is fixed, should be fixed by the end of the day ;)

**Comment by RicardoTheCoder** [comment]
@BarryAsthma just added a new version of the mod to curse, should be ready to update soon. It is version 1.1.1 and I would ask that you update it manually on your pack and test it. It should work fine now.

Exact copies will remain disabled, so I can better ensure that cows do not spawn with bugged fluids (that system is what prevents the exact copy ones)

**Comment by BarryAsthma** [comment]
Thanks for your reply. I tested the 1.1.1 version of minimoos. It now works, and it no longer seems to corrupt the savefile. However, it is still not possible to make an exact copy of the minimoo, If I set the spawner to spawn exact copies, it still spawns random minimoos, only at a slower rate. 

 Unfortunately, I wasn't able to test this update on my previously corrupted savefiles, since I already deleted them.

**Comment by svennieke** [comment]
To quote what @RicardoTheCoder said
"Exact copies will remain disabled, so I can better ensure that cows do not spawn with bugged fluids (that system is what prevents the exact copy ones)"

**Comment by scalda** [comment]
Thanks for the update @ricardothecoder I will get a update to FoolCraft out asap

**Comment by BarryAsthma** [comment]
@svennieke Aha, thanks. I must have missed that while reading the comment.

**Comment by DrWarFighter** [comment]
This issue is still occurring with the current version of Mini Moos, FC v2.3

**Comment by RicardoTheCoder** [comment]
@DrWarFighter What are you referring to? The crash when spawning cows or the exact copy problem?

The Exact Copy is disabled and will probably remain like that.

The spawning problem was tested with all outcomes and yield no problems or crashes, also regenerated corrupted saves. This was tested in the dev environment and in the pack itself.

**Comment by DrWarFighter** [comment]
@RicardoTheCoder As per @BarryAsthma post, spawning random mini moos crashed my world and continues to crash on world load; NullPointerException

**Comment by RicardoTheCoder** [comment]
@DrWarFighter Without providing me with a crash report I cannot see where in the code it is giving the error, so I cannot further help you without that report.

**Comment by DrWarFighter** [comment]
@RicardoTheCoder Sorry about that, thought I had attached it.  https://pastebin.com/CVt4vMVV

**Comment by RicardoTheCoder** [comment]
@DrWarFighter Found your problem, it is not in the mod actually. When you updated to FC 2.3 the twitch launcher might have bugged and didn't remove the version 1.1 of the mod, leaving it there, and that is what is being loaded. Therefore you get that error

This is from your crash report:
> UCHIJAAAA   minimoos{1.0} [MiniMoos] (MiniMoos-1.1-MC1.10.2.jar)

Check your mod folder and see if there is more than one version there, version 1.1.1 should be there too.

**Comment by DrWarFighter** [comment]
@RicardoTheCoder I just checked for a second version of Mini Moos, only 1.1.1 is/was installed. I then completely deleted the current instance of FC and reinstalled it, replacing the previously damaged save file which has now loaded up just fine. Thanks for your time.

**Comment by RicardoTheCoder** [comment]
@DrWarFighter I'm glad it is fixed. If you experience any more issues with the mod, please post an issue in the mod's issues so I can better keep track of it [MiniMoo's Issue Tracker](https://github.com/RicardoTheCoder/MiniMoos/issues)
