### ISSUE TITLE
Chunkloaders

### ISSUE THREAD

**Issue by hexangle** [scalda/FoolCraft#987]
I moved my base but lat my mubfarm in the old one and I put my base full of these weirding machine chunkloaders but they don't do anything and they surely doesn't load chunks. Any idea how to fix it?

**Comment by generrosity** [comment]
Are the weirding gadgets spinning?

**Comment by hexangle** [comment]
yes they are

**Comment by generrosity** [comment]
We've had occasional issues with them doing working, particularly if the server is slipping ticks, usual fixed by re clicking or re placing the weirding. But typically would stop spinning as I recall

**Comment by hexangle** [comment]
Ok i'll Try  replacing them

**Comment by hexangle** [comment]
nope still doesn't work I replaced them all and they are spinning
